- hosts: all
  become: yes
  roles:
    - common

- hosts: all
  become: yes
  roles:
    - docker

- hosts: master
  become: yes
  roles:
    - kubernetes

- hosts: workers
  become: yes
  tasks:
    - name: Join worker node to the cluster
      shell: "{{ hostvars['master']['join_command'] }}"
      when: hostvars['master']['join_command'] is defined